apiVersion: apps/v1
kind: Deployment
metadata:
  name: sddeploy-multi-pods
  labels:
    app: my-k8s-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-loadball-multi # Service will look for those PODS labels
  template:
    metadata:
      labels:
        app: demo-loadball-multi
    spec:
      containers:
        - name: loadball-web
          image: httpd:latest
          ports:
            - containerPort: 80 # Port on Pod
        
        - name: tomcat-web
          image: tomcat:8.5.38
          ports:
            - containerPort: 8080 # Port on Pod

---
apiVersion: v1
kind: Service
metadata:
  name: my-multi-pod-service
  labels:
    env: prod
    owner: sdan
spec:
  type: LoadBalancer
  selector:
    app: demo-loadball-multi # Selecting PODS with thise labels
  ports:
    - name       : httpd-app-listener
      protocol   : TCP
      port       : 80 # Port on Load Balancer
      targetPort : 80 # Port on POD

    - name       : tomcat-app-listener
      protocol   : TCP
      port       : 8888 # Port on Load Balancer
      targetPort : 8080 # Port on POD