apiVersion: apps/v1
kind: Deployment
metadata:
  name: sddeploy
  labels:
    app: my-k8s-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-loadball # Service will look for those PODS labels
  template:
    metadata:
      labels:
        app: demo-loadball
    spec:
      containers:
        - name: loadball-web
          image: httpd:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-single-pod-service
  labels:
    env: prod
    owner: sdan
spec:
  selector:
    app: demo-loadball # Selecting PODS with thise labels
  ports:
    - name       : app-listener
      protocol   : TCP
      port       : 80 # Port on Load Balancer
      targetPort: 80 # Port on POD
  type: LoadBalancer