apiVersion : apps/v1
kind : Deployment
metadata:
  name: my-web-deployment-replicas
  labels:
    app : my-k8s-application
    env: prod
    owner: SDan
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-replicas
  template:
    metadata:
      labels:
        app: demo-replicas
    spec:
      containers:
        - name: app-web
          image: httpd:2452
          ports:
            - containerPort: 8888