apiVersion : apps/v1
kind : Deployment
metadata:
  name: my-web-deployment
  labels:
    app : my-k8s-application
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: app-web
          image: httpd:bullseye
          ports:
            - containerPort: 8888